version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node
      - image: postgres
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
