version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node
        environment:
          NODE_ENV: test
          DATABASE_TEST_URL: "postgres://ubuntu@localhost:5432/app_test_db"
      - image: postgres
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: app_test_db
    steps:
      - checkout
      - run:
          name: update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: setup db
          command: 'sudo npm install -g db-migrate'
      - run:
          name: run migrations
          command: 'db-migrate up'
          environment:
            NODE_ENV: test
            DATABASE_TEST_URL: "postgres://ubuntu@localhost:5432/app_test_db"
      - run:
          name: test
          command: npm test
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
