version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node
        environment:
          NODE_ENV: test
          DATABASE_TEST_URL: "postgres://ubuntu@localhost:5432/app_test_db"
      - image: postgres
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: app_test_db
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Setup custom environment variables
          command: |
            echo 'export DATABASE_TEST_URL=postgres://ubuntu@localhost:5432/app_test_db' >> $BASH_ENV
            echo 'export NODE_ENV=test' >> $BASH_ENV
      - run:
          name: Test
          command: npm test
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
